language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: UEuUeivYYFeRFACJ1NHv2D5mh8vNugkZXylmIEZ4mwyKWRB/fGNiiSYGmGk1B9hUAzPUCFq8Jfr3EIyyzfrBQuB8L35v3stIMOfFlzZ0u4k+fEi8wkr6Q5UwVbjh7keJbGCERXh6xtnlZjIQswV9dTQco8lTZoBYc13A2RXfhATFv9QJ180EIopI4Iff4AJyHXaWHirJ3XGKJp9rzjCAFIeTLlqef8s2kXyirGcUrSc4zXMAinn8dq6FkqcsdIGVhKxbHoFGGspeclZHGzJByg4+cT1vXaj5+oSTBQM8GZmdnbXdAYKL9tg5uJkP+pd9j3OCC7L3tmxGG0LN6uaozBKkPrfc7yfMDeY8AhulgV+DT/LoK7oLENDSoBEoXPvdsaVLkT2KdEhZezGHc6RJJmowzPxINtxUQYuZxCvuqhKsMwhPUMTMW28S6Vw4hw9CoMWs5fatez0Ktxb28s7cFsvi8pb5Gz11ZDBpPNduwJ86fS3flq1yM8tzzpR1/DI5p6m8fEZL9t94y2VKbW6MN2gBnaIIcBX6I6/UnnFuw63CZzFve4u8znq8te3FVGa36Znc3G8eRXOSKAn6lDM4dEh4jNcI3eBleGpLRPwILOEI+OuTCK54fiFklidFRASNPH6O7pGFTrEsqAxrcc5/OPFR0zb00ng5gZsIE8C1IOw=
  app: vast-mesa-75968
