language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: 2pTxe8tzEEcveOvUm8yzshBLuLetjs21ObYsMFvhHkVKlTKqhMICGgfRHEB7X8xEOfJoKX2qYIeEEx7PS2Bbvop6839I+Orubj6u8QHGrwMonSNPyzZLFacrxcG2ZxTyjwnklTT5hp/7T95CTMo4VIOmHy1cZuReJkBEwXHmNcLKoaMgKJnXL2xCAQLOYIxQJ9h43laEoD9GvUGb0O5wAHzlY2HomqtV+ab63am9oEnSiugybKp0LxFFgGV4iRtNpcwabYZMgmWdwHKlZuliuzR4XTMT3f70oLLG9acDEAXQMCGhnWQPl0Pk54EVtHtDhyBWJCzcIZMPZNMPY17JOxPeS2hCp2PuXpnapKkuT6aYU4cjPkVErUxj1anqfcFzXD4wjWXxA5svo4kn9d/IZ9IEhitTZR78s0w5Of6aePiIuG8AaPQN//Y2T8yEVWBJgFilBEFTK2gubxf35sfjdS/r35ySvPNHDuaxls99JQA+lYFLeYy6QyqGAHPFcW9Z1okt1yWpCDWINWSfsvmY4spNsU4Jw1rYAL+phC5ZXgMXROPD3TOjaC1FoBwDpY8pNF9hcce0gvsPcOWnhF08zwQthNSWmcW0m3oN+dDME82DAx9pkRUZrPPmxRvoPNOpW3d1l0py+H0LejRVQjAcNQTJSYR06XMXiyT0ZTdCRq0=
  app: vast-mesa-75968
  script: Procfile
